# Generated by Django 4.1.5 on 2023-06-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
