# Generated by Django 4.1.5 on 2023-06-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_task_completed_alter_task_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='end_date',
        ),
    ]
